USE ROLE SYSADMIN;

-- Resume ingest tasks
ALTER TASK BRONZE.TASK_INGEST_ORDERS        RESUME;
ALTER TASK BRONZE.TASK_INGEST_ORDER_ITEMS   RESUME;
ALTER TASK BRONZE.TASK_INGEST_PAYMENTS      RESUME;
ALTER TASK BRONZE.TASK_INGEST_CUSTOMERS     RESUME;
ALTER TASK BRONZE.TASK_INGEST_RESTAURANTS   RESUME;
ALTER TASK BRONZE.TASK_INGEST_AGENTS        RESUME;

-- Resume Silver cleaning tasks
ALTER TASK BRONZE.TASK_CLEAN_ORDERS         RESUME;
ALTER TASK BRONZE.TASK_CLEAN_ORDER_ITEMS    RESUME;
ALTER TASK BRONZE.TASK_CLEAN_CUSTOMERS      RESUME;
ALTER TASK BRONZE.TASK_CLEAN_RESTAURANTS    RESUME;
ALTER TASK BRONZE.TASK_CLEAN_AGENTS         RESUME;
ALTER TASK BRONZE.TASK_CLEAN_PAYMENTS       RESUME;

-- Resume Gold loading task
ALTER TASK BRONZE.TASK_LOAD_GOLD            RESUME;

-- Verify all tasks are scheduled
SHOW TASKS IN SCHEMA FOOD_PLATFORM.BRONZE;