USE ROLE SYSADMIN;

-- SUSPEND ingest tasks
ALTER TASK BRONZE.TASK_INGEST_ORDERS        SUSPEND;
ALTER TASK BRONZE.TASK_INGEST_ORDER_ITEMS   SUSPEND;
ALTER TASK BRONZE.TASK_INGEST_PAYMENTS      SUSPEND;
ALTER TASK BRONZE.TASK_INGEST_CUSTOMERS     SUSPEND;
ALTER TASK BRONZE.TASK_INGEST_RESTAURANTS   SUSPEND;
ALTER TASK BRONZE.TASK_INGEST_AGENTS        SUSPEND;

-- SUSPEND Silver cleaning tasks
ALTER TASK BRONZE.TASK_CLEAN_ORDERS         SUSPEND;
ALTER TASK BRONZE.TASK_CLEAN_ORDER_ITEMS    SUSPEND;
ALTER TASK BRONZE.TASK_CLEAN_CUSTOMERS      SUSPEND;
ALTER TASK BRONZE.TASK_CLEAN_RESTAURANTS    SUSPEND;
ALTER TASK BRONZE.TASK_CLEAN_AGENTS         SUSPEND;
ALTER TASK BRONZE.TASK_CLEAN_PAYMENTS       SUSPEND;

-- SUSPEND Gold loading task
ALTER TASK BRONZE.TASK_LOAD_GOLD            SUSPEND;

-- Verify all tasks are scheduled
SHOW TASKS IN SCHEMA FOOD_PLATFORM.BRONZE;