-- Clear incorrect data from previous run
TRUNCATE TABLE SILVER.CLEAN_ORDERS;
TRUNCATE TABLE SILVER.CLEAN_ORDER_ITEMS;
TRUNCATE TABLE SILVER.CLEAN_CUSTOMERS;
TRUNCATE TABLE SILVER.CLEAN_RESTAURANTS;
TRUNCATE TABLE SILVER.CLEAN_AGENTS;
TRUNCATE TABLE SILVER.CLEAN_PAYMENTS;
TRUNCATE TABLE QUARANTINE.QUARANTINE_RECORDS;