USE ROLE SYSADMIN;
USE DATABASE FOOD_PLATFORM;
USE SCHEMA BRONZE;

-- APPEND_ONLY = TRUE because Bronze never updates or deletes
-- only new inserts matter for downstream processing

CREATE STREAM IF NOT EXISTS STREAM_RAW_ORDERS
  ON TABLE BRONZE.RAW_ORDERS
  APPEND_ONLY = TRUE
  COMMENT = 'Captures new rows in RAW_ORDERS for Silver processing';

CREATE STREAM IF NOT EXISTS STREAM_RAW_ORDER_ITEMS
  ON TABLE BRONZE.RAW_ORDER_ITEMS
  APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STREAM_RAW_PAYMENTS
  ON TABLE BRONZE.RAW_PAYMENTS
  APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STREAM_RAW_CUSTOMERS
  ON TABLE BRONZE.RAW_CUSTOMERS
  APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STREAM_RAW_RESTAURANTS
  ON TABLE BRONZE.RAW_RESTAURANTS
  APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STREAM_RAW_AGENTS
  ON TABLE BRONZE.RAW_AGENTS
  APPEND_ONLY = TRUE;

-- Verify
SHOW STREAMS IN SCHEMA FOOD_PLATFORM.BRONZE;