USE SCHEMA FOOD_PLATFORM.BRONZE;

-- Each task fires every 10 min BUT only runs the procedure
-- if the stream actually has new data (WHEN condition)
-- No data = task skips execution = no warehouse credits used

CREATE TASK IF NOT EXISTS TASK_CLEAN_ORDERS
  WAREHOUSE = TRANSFORM_WH
  SCHEDULE  = '10 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('FOOD_PLATFORM.BRONZE.STREAM_RAW_ORDERS')
AS
  CALL SILVER.SP_CLEAN_ORDERS_INCR();

CREATE TASK IF NOT EXISTS TASK_CLEAN_ORDER_ITEMS
  WAREHOUSE = TRANSFORM_WH
  SCHEDULE  = '10 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('FOOD_PLATFORM.BRONZE.STREAM_RAW_ORDER_ITEMS')
AS
  CALL SILVER.SP_CLEAN_ORDER_ITEMS_INCR();

CREATE TASK IF NOT EXISTS TASK_CLEAN_CUSTOMERS
  WAREHOUSE = TRANSFORM_WH
  SCHEDULE  = '10 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('FOOD_PLATFORM.BRONZE.STREAM_RAW_CUSTOMERS')
AS
  CALL SILVER.SP_CLEAN_CUSTOMERS_INCR();

CREATE TASK IF NOT EXISTS TASK_CLEAN_RESTAURANTS
  WAREHOUSE = TRANSFORM_WH
  SCHEDULE  = '10 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('FOOD_PLATFORM.BRONZE.STREAM_RAW_RESTAURANTS')
AS
  CALL SILVER.SP_CLEAN_RESTAURANTS_INCR();

CREATE TASK IF NOT EXISTS TASK_CLEAN_AGENTS
  WAREHOUSE = TRANSFORM_WH
  SCHEDULE  = '10 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('FOOD_PLATFORM.BRONZE.STREAM_RAW_AGENTS')
AS
  CALL SILVER.SP_CLEAN_AGENTS_INCR();

CREATE TASK IF NOT EXISTS TASK_CLEAN_PAYMENTS
  WAREHOUSE = TRANSFORM_WH
  SCHEDULE  = '10 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('FOOD_PLATFORM.BRONZE.STREAM_RAW_PAYMENTS')
AS
  CALL SILVER.SP_CLEAN_PAYMENTS_INCR();