USE SCHEMA FOOD_PLATFORM.SILVER;

-- These detect new rows in Silver
-- Trigger Gold loading when Silver has new clean data
CREATE STREAM IF NOT EXISTS STREAM_CLEAN_ORDERS
  ON TABLE SILVER.CLEAN_ORDERS
  APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STREAM_CLEAN_CUSTOMERS
  ON TABLE SILVER.CLEAN_CUSTOMERS
  APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STREAM_CLEAN_RESTAURANTS
  ON TABLE SILVER.CLEAN_RESTAURANTS
  APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STREAM_CLEAN_AGENTS
  ON TABLE SILVER.CLEAN_AGENTS
  APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STREAM_CLEAN_PAYMENTS
  ON TABLE SILVER.CLEAN_PAYMENTS
  APPEND_ONLY = TRUE;

SHOW STREAMS IN SCHEMA FOOD_PLATFORM.SILVER;