USE ROLE SYSADMIN;
USE SCHEMA FOOD_PLATFORM.BRONZE;

CREATE FILE FORMAT IF NOT EXISTS FF_CSV
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    -- RECORD_DELIMITER = '
    -- '
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '', 'N/A')
    EMPTY_FIELD_AS_NULL = TRUE
    -- DATE_FORMAT = 'YYYY-MM-DD'
    -- TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS'
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE FILE FORMAT IF NOT EXISTS FF_JSON
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    IGNORE_UTF8_ERRORS = TRUE;

CREATE FILE FORMAT IF NOT EXISTS FF_PARQUET
    TYPE = 'PARQUET'
    SNAPPY_COMPRESSION = TRUE; 

SHOW FILE FORMATS IN SCHEMA FOOD_PLATFORM.BRONZE;