USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS FOOD_PLATFORM;

CREATE SCHEMA IF NOT EXISTS FOOD_PLATFORM.BRONZE;

CREATE SCHEMA IF NOT EXISTS FOOD_PLATFORM.SILVER;

CREATE SCHEMA IF NOT EXISTS FOOD_PLATFORM.GOLD;

CREATE SCHEMA IF NOT EXISTS FOOD_PLATFORM.QUARANTINE;

SHOW SCHEMAS IN DATABASE FOOD_PLATFORM;